Repository Azure/pykusto, pull requests merged in 2020-01, with the labels that each got.

#45 Handle different and related types in iff
  pykusto/expressions.py
  pykusto/functions.py
  pykusto/query.py
  pykusto/type_utils.py
  setup.py
  test/test_functions.py
Labels: bug

#44 To nums
  pykusto/functions.py
  test/test_functions.py
Labels: enhancement

#46 Add project iml and some configuration fixes
  .gitignore
  .idea/modules.xml
  .idea/runConfigurations/Run_tests.xml
  pykusto.iml
Labels: infrastructure
