Repository Azure/pykusto, pull requests merged in 2020-05, with the labels that each got.

#72 Quote column name if it is a Kusto keyword + workaround
  pykusto/expressions.py
  pykusto/keywords.py
  test/test_expressions.py
Labels: bug

#75 bug-fix: adding new Kusto types also to the kql_converters
  .idea/dictionaries/pykusto.xml
  pykusto/expressions.py
  pykusto/kql_converters.py
  pykusto/type_utils.py
  setup.py
Labels: bug

#77 Add optional global client cache
  pykusto/client.py
  test/test_client.py
Labels: enhancement

#78 Add anyif, percentiles_array, sample-distinct, top-hitters, countof, ingestion_time
  .idea/dictionaries/pykusto.xml
  pykusto/enums.py
  pykusto/functions.py
  pykusto/query.py
  test/test_functions.py
  test/test_query.py
Labels: enhancement

#81 Update requirements
  pykusto/client.py
  setup.py
  test/test_base.py
  test/test_client.py
Labels: infrastructure
